upgrade: Coil, Kotlin, and other libraries to the latest versions
maruiz81/Coil-example pull request #1
Opened 2020-09-24 03:27 UTC by AdamSHurwitz

2020-10-11 21:23 UTC, maruiz81 commented on app/build.gradle
> +    implementation 'androidx.constraintlayout:constraintlayout:2.0.1'
Currently the last version 2.0.2. Sorry for taking so long to review it.

2020-10-11 21:24 UTC, maruiz81 requested changes

2020-10-11 21:24 UTC, maruiz81 commented on app/build.gradle
> +    implementation 'androidx.core:core-ktx:1.3.1'
The las version of core-ktx is 1.3.2

2020-10-19 20:07 UTC, AdamSHurwitz commented
I've updated the Gradle, Core KTX, and ConstraintLayout libraries in this repository as well. Thank you for reviewing!

2020-10-19 20:43 UTC, merged